FROM codercom/code-server:latest

# Install Python extensions
RUN code-server --install-extension ms-python.python && \
    code-server --install-extension ms-toolsai.jupyter && \
    code-server --install-extension njpwerner.autodocstring && \
    code-server --install-extension kevinrose.vsc-python-indent

# Set working directory
WORKDIR /home/coder/project

# Start code-server without authentication
CMD ["code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "none", "/home/coder/project"]
